services:
  db:
    image: mariadb
    container_name: message-db
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - message

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: message-app
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
    networks:
      - message
    depends_on:
      - db

networks:
  message:
    driver: bridge